import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Sidebar from "@/components/sidebar";
import { ThemeProvider } from "@/components/theme-provider";
import LinksNav from "@/components/links-nav";
import Providers from "@/components/providers";
import ProfileBar from "@/components/profile-bar/profile-bar";
import { userData } from "@/lib/session";

const inter = Inter({
  subsets: ["latin-ext"]
})

export const metadata: Metadata = {
  title: "Twitter",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const{isLoggedIn} = await userData()

  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/x-icon" href="/logo.webp"/>
      </head>
      <body
        className={`${inter.className} antialiased`}
      >


        <Providers>
          <div>
            <div className="sticky top-0 z-50">
              <Header />
            </div>
            <div className="w-full min-h-screen grid grid-cols-1 lg:grid-cols-5 gap-4">
              <div className=" hidden lg:col-span-1 lg:block border-r border-border">
                <div className="fixed left-[2%] h-screen ">
                  <Sidebar isLoggedIn={isLoggedIn}/>
                </div>
              </div>

              <div className="w-full col-span-1 lg:col-span-3 ">
                <div className="sticky top-16 z-40 w-full">
                  <LinksNav />
                </div>
                {children}
              </div>

              <div className="hidden w-1/4 lg:col-span-1 lg:block border-l border-border">
                <div className="fixed">
                  <ProfileBar/>
                </div>
              </div>
            </div>

          </div>


        </Providers>

      </body>
    </html>
  );
}
